language: php

php:
  - 7.2
  - 7.3

env:
  global:
    - DEFAULT=1
  
matrix:
  fast_finish: true

  include:
    - php: 7.3
      env: PHPCS=1 DEFAULT=0

    - php: 7.3
      env: COVERAGE=1 DEFAULT=0

before_script:
  - phpenv rehash

install:
  - composer self-update
  - composer install --prefer-dist --no-interaction --dev
  - if [[ $PHPSTAN = 1 ]]; then composer stan-setup; fi

script:
  - if [[ $DEFAULT = 1 ]]; then composer test; fi
  - if [[ $COVERAGE = 1 ]]; then composer coverage-test; fi
  - if [[ $PHPCS = 1 ]]; then composer cs-check; fi
  - if [[ $PHPSTAN = 1 ]]; then composer stan; fi

after_success:
  - if [[ $COVERAGE = 1 ]]; then bash <(curl -s https://codecov.io/bash); fi

  
notifications:
  email: false
